artifactory:
  extends:
    file: docker-compose-common.yml
    service: artifactory
sonarqube:
  extends:
    file: docker-compose-common.yml
    service: sonarqube
mysql:
  extends:
    file: docker-compose-common.yml
    service: mysql
cadvisor:
  extends:
    file: docker-compose-common.yml
    service: cadvisor
