jenkins:
  # extends:
  #   file: docker-compose-common.yml
  #   service: jenkins
  build: dockerfiles/jenkins
  ports:
    - "8080"
  volumes_from:
    - devopsstack_jenkins-data_1 # Name will change depending on scale etc
    # - devopsstack_ruby_1 # Used for running Ruby on Jenkins
  links:
    - sonarqube
    - artifactory
